// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace bookingOrganizer_Api.Models;

public partial class BookingInfo
{
    public int BookingId { get; set; }

    public int GroupId { get; set; }

    public int TypeBookingId { get; set; }

    public DateTime Date { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public string Address { get; set; }

    public string PurchaseMethod { get; set; }

    public string SeatNumber { get; set; }

    public string Notes { get; set; }

    public virtual Group Group { get; set; }

    public virtual TypeBooking TypeBooking { get; set; }
}