// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace bookingOrganizer_Api.Models;

public partial class Group
{
    public int GroupId { get; set; }

    public string GroupName { get; set; }

    public virtual ICollection<BookingInfo> BookingInfos { get; set; } = new List<BookingInfo>();

    public virtual ICollection<GroupMember> GroupMembers { get; set; } = new List<GroupMember>();
}