// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace bookingOrganizer_Api.Models;

public partial class TypeBooking
{
    public int TypeBookingId { get; set; }

    public string TypeName { get; set; }

    public virtual ICollection<BookingInfo> BookingInfos { get; set; } = new List<BookingInfo>();
}